import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import TopNotifs from "@/components/topnotifs/TopNotifs";
import Logo from "@/components/logo/Logo";
import Navbar from "@/components/navbar/Navbar";
import AtomLoader from "@/components/AtomLoader";
import Footer from "@/components/footer/Footer";

const lato = Lato({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata: Metadata = {
  title: "The Source",
  description: "Generated by Max",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <AtomLoader />

        <div style={{ backgroundColor: "#000", display: "grid" }}>
          <TopNotifs />
          <Logo />
          <Navbar />
        </div>

        {children}

        <Footer />
      </body>
    </html>
  );
}
